<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [1]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'

In [2]:
greeting("super man")

'Hello super man!'

In [3]:
greeting(name="Super Man")

'Hello Super Man!'

In [4]:
greet=greeting('Super Man')
print(greet)

Hello Super Man!


In [5]:
print(greeting(name='Super Man'))

Hello Super Man!


In [6]:
def basic_stats(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()

In [12]:
list_min,list_max,list_mean = basic_stats([1,2,3,4,5])
print(list_min,list_max,list_mean)

1 5 3.0


### 1.2 Named functions that don’t return

In [ ]:
#example: print --> save data


### 1.3 Anonymous functions

In [13]:
my_short_function = lambda name: f"Hello {name}!"

In [17]:
my_short_function(name="superman")

'Hello superman!'

In [16]:
my_short_function("aa")

'Hello aa!'

In [18]:
try_function = lambda hh: f"try out this {hh}"

In [19]:
try_function("hjdcbmnbchrbhj")

'try out this hjdcbmnbchrbhj'

In [22]:
#"Sorted" by default is based on comparing 
#the first elements of the sub-lists.

In [25]:
numbers=[[9, 0, 10],
         [7, 6, 11],
         [7, 2, 12],
         [6, 2, 13],
         [4, 4, 14],
         [4, 5, 15],
         [3, 3, 16],
         [4, 7, 17],
         [1, 7, 18],
         [6, 9, 19]]

sorted(numbers)

[[1, 7, 18],
 [3, 3, 16],
 [4, 4, 14],
 [4, 5, 15],
 [4, 7, 17],
 [6, 2, 13],
 [6, 9, 19],
 [7, 2, 12],
 [7, 6, 11],
 [9, 0, 10]]

In [26]:
sorted(numbers, key=lambda x: x[1])

[[9, 0, 10],
 [7, 2, 12],
 [6, 2, 13],
 [3, 3, 16],
 [4, 4, 14],
 [4, 5, 15],
 [7, 6, 11],
 [4, 7, 17],
 [1, 7, 18],
 [6, 9, 19]]

In [27]:
sorted(numbers,key=lambda x:sum(x))

[[9, 0, 10],
 [7, 2, 12],
 [6, 2, 13],
 [4, 4, 14],
 [3, 3, 16],
 [7, 6, 11],
 [4, 5, 15],
 [1, 7, 18],
 [4, 7, 17],
 [6, 9, 19]]

### 1.4 Optional arguments

In [28]:
def greeting(name='no one'):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'

In [30]:
greeting()

'Hello no one!'

In [31]:
greeting('aa')

'Hello aa!'

In [33]:
greeting('Batman')

'Hello Batman! So, nice to meet you!'

In [34]:
#in Print
#file:a file-like object (stream); defaults to the current sys.stdout.
#sep:string inserted between values, default a space.
#end:string appended after the last value, default a newline.
#flush: whether to forcibly flush the stream.
#Type:builtin_function_or_method

In [45]:
print('I', 'am', 'Batman!') 

print('I', 'am', 'Batman!', sep='---')  

print('I', 'am', 'Batman!', end='\n hii')  

I am Batman!
I---am---Batman!
I am Batman!
 hii

## 2 The importance of functions?

### 2.1 An argument for functions

In [46]:
#GOOD about Function
#Abstraction of details 
#Reusability of code
#Maintainability of code

### 2.2 A word of caution

In [47]:
#Having too many functions 
#can make it difficult to read your code 
#increase computational overheads. 


## Exercise 1 :  Do you know why?

the second "return" is aligned with "if", so it belong to the "def" function. hence, "else" is not required.

## Exercise 2 :  Calculator functions

In [13]:
def basic_stats(numbers):
    np_numbers=np.array(numbers)
    
def add(x,y):
    return x+y
def substract(x,y):
    return x-y
def multiply(x,y):
    return x*y
def devide(x,y):
    if any (y==0):
        return "the devisor can not be 0!"
    else:
        return x/y

In [14]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 0])

print (add(x,y))
print (substract(x,y))
print (multiply(x,y))
print (devide(x,y))

[100 100 100 100  27]
[-28 -32 -12  52  27]
[2304 2244 2464 1824    0]
the devisor can not be 0!


## Exercise 3 :  max_info() with NumPy

In [82]:
def max_info(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.max(), np_numbers.argmax()

In [99]:
list_max,list_argmax= max_info([40, 27, 83, 44, 74, 51, 76, 77, 10, 49])
print(list_max,list_argmax)

83 2
