<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Good)</span></div>

## 1 Check, balances and contingencies

### 1.1 assert

In [1]:
# assert stops the flow if the condition fails

In [17]:
x = 10
assert x >= 0, "x is becoming negative!"

In [71]:
x = -1
assert x >= 0, "x is becoming negative!"

AssertionError: x is becoming negative!

In [72]:
x = -1
assert x >= 0, print ("x is becoming negative!")

x is becoming negative!


AssertionError: None

### 1.2 try-except

In [21]:
number=input("Give me a number and I will calculate its square.")
square=int(number)**2
print(f'The square of {number} is {square}!')

Give me a number and I will calculate its square.2
The square of 2 is 4!


In [23]:
try:
    number=input("Give me a number and I will calculate its square.")
    square=int(number)**2
    print(f'The square of {number} is {square}!')
except:
    print(f"Oh oh! I cannot square {number}!")

Give me a number and I will calculate its square.ii
Oh oh! I cannot square ii!


## 2 Some loose ends

### 2.1 Positional, keyword and default arguments

In [32]:
def funny_add(a, b, c=1):
    return a + 10*b + 100*c

<function funny_add at 0x10f3368c0>


In [41]:
print (funny_add(1, 2) )
#Two positional, 1 default

121


In [42]:
print (funny_add(a=1,b=2))

121


In [40]:
#Two keyword, 1 default

In [43]:
print (funny_add(1, b=2) )

121


In [44]:
# One positional, 1 keyword, 1 default

In [ ]:
print (funny_add(1, 2, 3))

In [45]:
# Three positional

In [ ]:
print (funny_add(1, c=3, b=2))

In [ ]:
#One positional, 2 keyword

In [39]:
print (funny_add(c=3, b=1, a=2))

321
321
312


In [49]:
#Three keyword

In [52]:
funny_add(a=2, b=1,3)
# Won't work.
# Keywords cannot be followed by 
# positional

SyntaxError: positional argument follows keyword argument (2233576499.py, line 1)

### 2.2 Docstrings

In [56]:
def funny_add(a, b, c=1):
    '''A test function to demonstrate how 
    positional, keyword and default arguments 
    work.'''
    return a + 10*b + 100*c

In [57]:
help(funny_add)

Help on function funny_add in module __main__:

funny_add(a, b, c=1)
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.



### 2.3 Function are first class citizens

In [58]:
def my_function(angle, trig_function):
        return trig_function(angle)

In [59]:
my_function(np.pi/2, np.sin) 
#May I ask
#Why we use "np" here?

1.0

In [60]:
my_function(np.pi/2, np.cos)

6.123233995736766e-17

In [61]:
my_function(np.pi/2, lambda x: np.cos(2*x))

#May I ask why the lambda here 
#is recognised as a trig_function?

-1.0

### 2.4 More unpacking

In [63]:
x, y, z = [1, 2, 3]
print(x, y, z)

1 2 3


In [64]:
x, y, z = np.array([1, 2, 3])
print(x, y, z)

1 2 3


In [70]:
x, *y, z = np.array([1, 2, 3, 4, 5])
print(x, y, z)

1 [2, 3, 4] 5


In [68]:
x, *_, y = [1, 2, 3, 4, 5]
print(x, y)

1 5


## Exercise 1 :  A better calculator I

1. Create four functions add(x, y), subtract(x, y), multiply(x, y) and divide(x, y) that realise the operations x+y, x-y, x*y and x/y respectively.
   1. For the division case, remember to add an if condition to admonish the division user by zero.
   1. You will have to use the function exit()23 to force Python to stop.
1. Test your functions with the following NumPy arrays(!)

In [306]:
def basic_stats(numbers):
    np_numbers=np.array(numbers)
    
def add(x,y):
    return x+y
def substract(x,y):
    return x-y
def multiply(x,y):
    return x*y
def devide(x,y):
    assert all(y!=0), print ("The devisor can not be 0!")
    return x/y

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

print (add(x,y))
print (substract(x,y))
print (multiply(x,y))
print (devide(x,y))


[100 100 100 100 100]
[-28 -32 -12  52 -46]
[2304 2244 2464 1824 1971]
[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]


## Exercise 2 :  A better calculator II

In [1]:
a=np.array([36, 34, 44, 76, 27])
b=np.array([64, 66, 56, 24, 73])        

def basic_stats(numbers):
    np_numbers=np.array(numbers)   
    
def add(a,b):
    return a+b
print (add(a,b))

def substract(a,b):
    return a-b
print (substract(a,b))

def multiply(a,b):
    return a*b
print (multiply(a,b))


[100 100 100 100 100]
[-28 -32 -12  52 -46]
[2304 2244 2464 1824 1971]


In [2]:
try:
    while all (b!=0) == True:
        def devide(a,b):
            return a/b
        print (devide(a,b))
except: 
    print ("The devisor can not be 0!")

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

