<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [1]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [4]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])


In [5]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                 }

In [ ]:
#take away

#three basic ways of storing data:
#1. lists,
#2. NumPy arrays 
#3. dictionaries.

### 1.2 Accessing data from a list (or array)

In [8]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [9]:
print(py_real_names[0])
print(py_super_names[0])

Natasha Romanoff
Black Widow


In [12]:
print(py_super_names[2])

Doctor Strange


In [11]:
print(py_super_names[-1])

Doctor Strange


In [ ]:
# take away
# forward and inversed indexing both work

### 1.3 Accessing data from a dictionary

In [13]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

In [22]:
print (superhero_info["Natasha Romanoff"])

Black Widow


In [26]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [27]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

### 1.4 Higher dimensional lists

In [35]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

print(py_superhero_info[1])
print(py_superhero_info[-1])

['Tony Stark', 'Iron Man']
['Stephen Strange', 'Doctor Strange']


## 2 Lists vs. Arrays

### 2.1 Size

In [41]:
py_list_2d = [[1,"A"],[2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]
             ]
np_array_2d = np.array(py_list_2d)


In [37]:
len(py_list_2d)

10

In [44]:
len(np_array_2d)

10

In [43]:
np_array_2d.shape

(10, 2)

In [ ]:
#arrays like having a single data type
#lists are more accommodating

### 2.2 Arrays are fussy about type

In [46]:
py_list = [1, 1.5, 'A']
np.array(py_list)

array(['1', '1.5', 'A'], dtype='<U32')

In [ ]:
#RMB: 
#NumPy arrays tolerate only a single type

### 2.3 Adding a number

In [55]:
py_list = [1,2,3,4,5]
np_array = np.array(py_list)

In [57]:
py_list + 10
#list cannot simply add element

TypeError: can only concatenate list (not "int") to list

In [68]:
np_array + 10

array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [69]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)


In [71]:
py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [72]:
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

### 2.5 Multiplying by a Number

In [73]:
py_list = [1,2,3,4,5]
np_array = np.array(py_list)

In [74]:
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [75]:
np_array*2

array([ 2,  4,  6,  8, 10])

### 2.6 Squaring

In [78]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [76]:

py_list**2


TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [79]:
#py cannot calculate square!

In [77]:
np_array**2

array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         


In [80]:
py_list == 3

False

In [81]:
py_list > 3

TypeError: '>' not supported between instances of 'list' and 'int'

In [82]:
np_array == 3

array([False, False,  True, False, False])

In [85]:
np_array > 3

array([False, False, False,  True,  True])

In [88]:
#in np, numbers can be compared separately
#May I conclude like this?

### 2.8 Mathematics

In [87]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         


In [89]:
sum(py_list)

15

In [91]:
max(py_list)

5

In [92]:
min(py_list)

1

In [93]:
py_list.sum()

AttributeError: 'list' object has no attribute 'sum'

In [94]:
sum(np_array)

15

In [95]:
max(np_array)

5

In [96]:
min(np_array)

1

In [97]:
mean(np_array)

#mean does not work in this format

NameError: name 'mean' is not defined

In [98]:
np_array.sum()

15

In [99]:
np_array.max()

5

In [100]:
np_array.min()

1

In [102]:
np_array.mean()
#calculated mean give 1dp

3.0

In [ ]:
#Take Away
#list works on the whole list.
#array works on individual elements.

## Exercise 1 :  Total recall?

1. Two similarities between lists and arrays.
   1. they can both store data
   1. data stored inside both ist and arrays are accessed in a similar way
1. Two differences between lists and arrays.
   1. python list is operated as a whole list by python, but np array is operated with individual elements by python.
   1. python list accept different data types, but array only allows one type. (if you put different types into an array, it will convert for you)
1. What is a dictionary?
   1. dictionary store different types of related data in one structure


## Exercise 2 :  Index me

In [106]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
                    
print(py_list[0],
      py_list[2],
      py_list[4],
      py_list[6],
      py_list[8])   



a1 c3 e5 g7 i9


## Exercise 3 :  Capitalise Heros

In [112]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper() 
superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper() 
superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper() 
print(superhero_info['Tony Stark'])
print(superhero_info['Natasha Romanoff'])
print(superhero_info['Stephen Strange'])

IRON MAN
BLACK WIDOW
DOCTOR STRANGE


In [114]:
#Just to try for fun
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Iron Man'] = superhero_info['Iron Man'].upper() 
superhero_info['Black Widow'] = superhero_info['Black Widow'].upper() 
superhero_info['Doctor Strange'] = superhero_info['Doctor Strange'].upper() 
print(superhero_info['Tony Stark'])
print(superhero_info['Natasha Romanoff'])
print(superhero_info['Stephen Strange'])

#Take away
#Dictionay only indexes keys, it cannot index value

KeyError: 'Iron Man'

## Exercise 4 :  How many ones

In [123]:
py_list = [45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
           99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
           83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
           1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
           8, 37, 35, 1, 89, 29, 86, 19, 43, 61]
np_array_numbers = np.array(py_list)         
np_array_cal1 = np_array_numbers == 1
np_array_cal1.sum()

9