<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [13]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

x = np_array


In [14]:
x[0]

'a1'

In [17]:
x[-1]

'j10'

In [19]:
x[0:3]

array(['a1', 'b2', 'c3'], dtype='<U3')

In [16]:
x[1:6]

array(['b2', 'c3', 'd4', 'e5', 'f6'], dtype='<U3')

In [21]:
x[1:6:2]

array(['b2', 'd4', 'f6'], dtype='<U3')

In [23]:
x[5:]

array(['f6', 'g7', 'h8', 'i9', 'j10'], dtype='<U3')

In [22]:
x[:5]
# I think this should be Index 0 to 4
#but on sp2273 website, it stated Index 0 to 5

array(['a1', 'b2', 'c3', 'd4', 'e5'], dtype='<U3')

In [24]:
x[5:2:-1]

array(['f6', 'e5', 'd4'], dtype='<U3')

In [25]:
x[::-1]

array(['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1'],
      dtype='<U3')

In [4]:
x = py_list
x[-1]

'j10'

In [11]:
x = py_list
x[1:6]

['b2', 'c3', 'd4', 'e5', 'f6']

In [26]:
#NOTE: only array will give a format of array([]), dtype=''

### 1.2 Subsetting by masking (Arrays only)

In [44]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
print(my_mask)

[False False False  True  True  True  True  True  True  True]


In [45]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [48]:
#subsetting by masking 
#ONLY works with NUMPY arrays.

In [46]:
np_array[np_array>3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [47]:
np_array[~(np_array > 3)]

array([1, 2, 3])

In [49]:
#'~' = 'NOT'

In [50]:
np_array[(np_array > 3) & (np_array < 8)]

array([4, 5, 6, 7])

In [52]:
#'&' = 'AND'

In [53]:
np_array[(np_array < 3) | (np_array > 8)]

array([ 1,  2,  9, 10])

In [54]:
#'|' = 'OR'

### 1.3 Indexing & Slicing 2D Lists

In [57]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

In [58]:
py_list_2d[3]

[4, 'D']

In [ ]:
#记：第一个编号是 0！！

In [59]:
py_list_2d[3][0]

4

In [ ]:
#second [] means 
#element at certain position 

In [60]:
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [61]:
py_list_2d[:3][0]

[1, 'A']

In [62]:
py_list_2d[3:6][0]

[4, 'D']

In [63]:
#second [0] here means 
#the first of the list 

### 1.4 Indexing & Slicing 2D Arrays

In [64]:
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])

In [65]:
np_array_2d[3]

array(['4', 'D'], dtype='<U21')

In [66]:
np_array_2d[3, 0]

'4'

In [67]:
np_array_2d[:3]

#May I ask why 
#For array,
#Different positions are shown on different lines
#But for List, they are all on the same line

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

In [68]:
np_array_2d[:3, 0]

array(['1', '2', '3'], dtype='<U21')

In [71]:
np_array_2d[:, 0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

In [72]:
#NOTE: using only ':' is for all

### 1.5 Growing lists

In [73]:
x=[1]*10
x             

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [85]:
x=[1]
x=x+[2]
x=x+[3]
x=x+[4]
x
#x here is an array

[1, 2, 3, 4]

In [86]:
x=[1]
x+=[2]
x+=[3]
x+=[4]
x

[1, 2, 3, 4]

In [83]:
x=[1]
x+=[2, 3, 4]
x

[1, 2, 3, 4]

In [88]:
x=[1]
x=[2, 3, 4]+x
x

[2, 3, 4, 1]

In [91]:
x=[1]
x=[2, 3, 4]+x
x

[2, 3, 4, 1]

In [92]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

## 2 Some loose ends

### 2.1 Tuples

In [95]:
#similar to lists
#BUT
#use ( )
#cannot be changed after creation

In [96]:
a=(1, 2, 3)
print(a[0])

1


In [105]:
a[0]=-1
a[0] += [10]
#do not work
#Tuples cannot be changed

TypeError: unsupported operand type(s) for +=: 'int' and 'list'

### 2.2 Be VERY careful when copying

In [118]:
##NEVER USE
x=[1, 2, 3]
y=x
z=x
x+=[5]
print(x,y,z)
#change one change others

[1, 2, 3, 5] [1, 2, 3, 5] [1, 2, 3, 5]


In [117]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()
x+=[5]
print(x,y,z)

[1, 2, 3, 5] [1, 2, 3] [1, 2, 3]


## Exercise 1 :  Total recall?

1. *Subsetting: to select (either one element or a range of element)*
1. Indexing: Selecting one element
1. Slicing: Selecting a range of elements
1. Masking: allows an array to be shown in a "True/False" format. Thus, we can ask NumPy to show only "True" Value.

## Exercise 2 :  Show me the ‘odd’ letters

In [136]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

np_array_2dint=np_array_2d[:, 0].astype(int)
print(np_array_2dint)

[ 1  3  2  4  5  7  6  8 10  9]


In [134]:
np_array_remainder = np_array_2dint%2

print(np_array_remainder)

[1 1 0 0 1 1 0 0 0 1]


In [140]:
my_mask = np_array_remainder > 0
print(my_mask)

[ True  True False False  True  True False False False  True]


In [159]:
np_array[my_mask]

array([ 1,  2,  5,  6, 10])

In [162]:
print(np_array_2d[my_mask, 1])

['A' 'C' 'E' 'G' 'I']
